platform :ios, '6.0'
inhibit_all_warnings!

# Zhaoyang's framework
pod "Reddydog", :git => 'https://github.com/yangyangduo/Reddydog.git'

# Third
pod 'PinYin4Objc', '~> 1.1.1'
pod 'SDWebImage', '~> 3.5.2'